config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :user_bets
  resources :experiments
  resources :users

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  has_many :user_bets, dependent: :destroy

  validates :name, presence: true
  validates :metric, presence: true
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update]

  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all
    @user_bets = UserBet.all

    # Build hash for Users and Bets to print
    @user_bets_table = {}
    @experiments.each do |experiment|
      @user_bets_table[experiment.id] = {}
    end
    @user_bets.each do |user_bet|
      @user_bets_table[user_bet.experiment_id][user_bet.user_id] = user_bet.user_bet
    end

    # Create a list of Experiments. Show results for 14 days past results date.
    @active_experiments = Experiment.where('estimated_result_date > ?', Time.zone.now - 7.days)

    # Create a list of Users.
    # TODO Filter for only relevant users (i.e. those with active bets)
#    @active_bet_users = Set.new
#    @all_users = User.all
#    @all_users.each do |user|
#      @active_bet_users.add(user)
#    end

#    @active_bet_users = User.all

    @active_bet_users = Set.new

    @active_experiments.each do |experiment|
      experiment.user_bets.each do |user_bet|
        @active_bet_users.add(User.find_by_id(user_bet.user_id))
      end
    end
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render :show, status: :created, location: @experiment }
      else
        format.html { render :new }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { render :show, status: :ok, location: @experiment }
      else
        format.html { render :edit }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url, notice: 'Experiment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:name, :metric, :estimated_result_date, :bet_by_date, :result)
    end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Experiment name" %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :metric %><br>
    <%= f.text_field :metric, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :estimated_result_date %><br>
    <%= f.date_select :estimated_result_date,
        {:order => [:day, :month, :year], :start_year => 2016, :end_year => 2017},
        {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :bet_by_date %><br>
    <%= f.date_select :bet_by_date,
        {:order => [:day, :month, :year], :start_year => 2016, :end_year => 2017},
        {:class => "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :result %><br>
    <%= f.text_field :result, :class => 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Experiment', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/experiments/edit.html.erb
<h1>Editing Experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

app/views/experiments/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">ACTIVE BETS</div>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <% @active_experiments.each do |experiment| %>
          <th>
            <%= experiment.name %>
            <% if current_user.present? && current_user.admin? %>
              | <%= link_to "delete", experiment, method: :delete,
                                            data: { confirm: "You sure?" } %>
            <% end %>
          </th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <tr>
        <td>Metrics</td>
        <% @active_experiments.each do |experiment| %>
          <td><%= experiment.metric %></td>
        <% end %>
      </tr>
      <tr>
        <td>Estimated Results Date</td>
        <% @active_experiments.each do |experiment| %>
          <td><%= experiment.estimated_result_date %></td>
        <% end %>
      </tr>
      <% @active_bet_users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <% @active_experiments.each do |experiment| %>
            <td><%= @user_bets_table[experiment.id][user.id] %></td>
          <% end %>
        </tr>
      <% end %>
      <tr class="info">
        <td>RESULT</td>
        <% @active_experiments.each do |experiment| %>
          <td><%= experiment.result %></td>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

<br>

<div>
  <%= link_to 'Place Your Bets (as to a Feature’s Benefits)', new_user_bet_path, style: "float: left" %>
  <%= link_to 'Add Experiment', new_experiment_path, style: "float: right" %>
</div>

app/views/experiments/new.html.erb
<h1>Add an Experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @experiment.name %>
</p>

<p>
  <strong>Metric:</strong>
  <%= @experiment.metric %>
</p>

<p>
  <strong>Estimated result date:</strong>
  <%= @experiment.estimated_result_date %>
</p>

<p>
  <strong>Actual result date:</strong>
  <%= @experiment.bet_by_date %>
</p>

<p>
  <strong>Result:</strong>
  <%= @experiment.result %>
</p>

<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>