config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :account_activations, only: [:edit]
  resources :user_bets
  resources :experiments
  resources :users

end

app/models/user_bet.rb
class UserBet < ActiveRecord::Base
  belongs_to :user
  belongs_to :bet

  validates :user_id, presence: true
  validates :experiment_id, presence: true
end

app/controllers/user_bets_controller.rb
class UserBetsController < ApplicationController
  before_action :set_user_bet, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  # GET /user_bets
  # GET /user_bets.json
  def index
    @user_bets = UserBet.all
  end

  # GET /user_bets/1
  # GET /user_bets/1.json
  def show
  end

  # GET /user_bets/new
  def new
    @user_bet = UserBet.new

    # Create a list of Experiments.
    # TODO Filter for only relevant experiments (i.e. those before the bet date)
    @open_bet_experiments = Experiment.where('bet_by_date > ?', Time.zone.now)
  end

  # GET /user_bets/1/edit
  def edit
  end

  # POST /user_bets
  # POST /user_bets.json
  def create
    @user_bet = current_user.user_bets.build(user_bet_params)

    if @user_bet.save
      flash[:success] = "Your bet is in!"
      redirect_to experiments_url
    else
      format.html { render :new }
      format.json { render json: @user_bet.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /user_bets/1
  # PATCH/PUT /user_bets/1.json
  def update
    respond_to do |format|
      if @user_bet.update(user_bet_params)
        format.html { redirect_to @user_bet, notice: 'User bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_bet }
      else
        format.html { render :edit }
        format.json { render json: @user_bet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_bets/1
  # DELETE /user_bets/1.json
  def destroy
    @user_bet.destroy
    respond_to do |format|
      format.html { redirect_to user_bets_url, notice: 'User bet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_bet
      @user_bet = UserBet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_bet_params
      params.require(:user_bet).permit(:experiment_id, :user_bet)
    end
end

app/helpers/user_bets_helper.rb
module UserBetsHelper
end

app/views/user_bets/_form.html.erb
<%= form_for(@user_bet) do |f| %>
  <% if @user_bet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_bet.errors.count, "error") %> prohibited this user_bet from being saved:</h2>

      <ul>
      <% @user_bet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :experiment_id %><br>
    <%= collection_select(:user_bet, :experiment_id, @open_bet_experiments, :id, :name, {}, {:class=>'form-control'}) %>
  </div>
  <div class="form-group">
    <%= f.label "Your Bet" %><br>
    <%= f.text_field :user_bet, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit 'Place Bet', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/user_bets/edit.html.erb
<h1>Editing User Bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_bet %> |
<%= link_to 'Back', user_bets_path %>

app/views/user_bets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>The Big Board of Bets</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Experiment</th>
      <th>User Bet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_bets.each do |user_bet| %>
      <tr>
        <td><%= user_bet.user_id %></td>
        <td><%= user_bet.experiment_id %></td>
        <td><%= user_bet.user_bet %></td>
        <td><%= link_to 'Show', user_bet %></td>
        <td><%= link_to 'Edit', edit_user_bet_path(user_bet) %></td>
        <td><%= link_to 'Destroy', user_bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User bet', new_user_bet_path %>

app/views/user_bets/new.html.erb
<h1>New User Bet</h1>

<%= render 'form' %>

<%= link_to 'Back', user_bets_path %>

app/views/user_bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_bet.user_id %>
</p>

<p>
  <strong>Bet:</strong>
  <%= @user_bet.experiment_id %>
</p>

<p>
  <strong>Bet:</strong>
  <%= @user_bet.user_bet %>
</p>

<%= link_to 'Edit', edit_user_bet_path(@user_bet) %> |
<%= link_to 'Back', user_bets_path %>